services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"
    env_file:
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy  # Ensures Mongo is ready before backend starts
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:5100

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  mongo_data:
